version: "3.9"

services:
  webserver:
    build: .
    container_name: webserver
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database

  artisan:
    build: .
    container_name: artisan
    entrypoint: ["php","/var/www/html/artisan"]
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql

volumes:
  data:
